# docker-compose.yml
version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/home/app
      - /home/app/node_modules/
    depends_on:
      - mysql
    ports:
      - "8000:8000"
      - "9229:9229"

  mysql:
    image: mysql:5.7
    command: --sql_mode=""
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

#  rabbitmq:
#    image: rabbitmq:3-management
#    hostname: my-rabbit
#    ports:
#      - 5672:5672
#      - 15672:15672